export const tokens = {
  color: {
    bg: '#F5F8FD',
    surface: '#FFFFFF',
    textPrimary: '#0B0F18',
    textSecondary: '#6B7280',
    textCounter: '#57626F',
    textCommentsHeader: '#68727D',
    sortLink: '#6115CD',
    border: '#EEF0F5',
    accent: '#6D28D9',
    skeletonBase: '#EEF2F7',
    skeletonHighlight: 'rgba(255,255,255,0.75)',
    overlay: 'rgba(0,0,0,0.38)',
    feedLikeActive: '#FF2B75',
    feedLikeActiveContrast: '#FFEAF1',
    feedPillNeutral: '#EFF2F7',
  },
  spacing: {
    4: 4,
    6: 6,
    8: 8,
    10: 10,
    12: 12,
    14: 14,
    16: 16,
  },
  radius: {
    8: 8,
    12: 12,
    16: 16,
    22: 22,
    pill: 999,
  },
  typography: {
    authorName: {
      fontFamily: 'Manrope_700Bold',
      fontSize: 15,
      lineHeight: 20,
      fontWeight: '700' as const,
    },
    title: {
      fontFamily: 'Manrope_700Bold',
      fontSize: 18,
      lineHeight: 26,
      fontWeight: '700' as const,
    },
    body: {
      fontFamily: 'Manrope_500Medium',
      fontSize: 15,
      lineHeight: 20,
      fontWeight: '500' as const,
    },
    bodySemibold: {
      fontFamily: 'Manrope_600SemiBold',
      fontSize: 15,
      lineHeight: 20,
      fontWeight: '600' as const,
    },
    meta: {
      fontFamily: 'Manrope_500Medium',
      fontSize: 12,
      lineHeight: 16,
      fontWeight: '500' as const,
    },
    segmentTabInactive: {
      fontFamily: 'Manrope_500Medium',
      fontSize: 13,
      lineHeight: 18,
      fontWeight: '500' as const,
    },
    segmentTabActive: {
      fontFamily: 'Manrope_700Bold',
      fontSize: 13,
      lineHeight: 18,
      fontWeight: '700' as const,
    },
    counter: {
      fontFamily: 'Manrope_700Bold',
      fontSize: 13,
      lineHeight: 18,
      fontWeight: '700' as const,
    },
    commentsCountTitle: {
      fontFamily: 'Manrope_600SemiBold',
      fontSize: 15,
      lineHeight: 20,
      fontWeight: '600' as const,
    },
    sortLabel: {
      fontFamily: 'Manrope_500Medium',
      fontSize: 15,
      lineHeight: 20,
      fontWeight: '500' as const,
    },
    buttonLabel: {
      fontFamily: 'Manrope_600SemiBold',
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '600' as const,
    },
    errorTitle: {
      fontFamily: 'Manrope_600SemiBold',
      fontSize: 16,
      lineHeight: 22,
      fontWeight: '600' as const,
      textAlign: 'center' as const,
    },
    micro: {
      fontFamily: 'Manrope_700Bold',
      fontSize: 11,
      lineHeight: 14,
      fontWeight: '700' as const,
    },
    link: {
      fontFamily: 'Manrope_600SemiBold',
      fontSize: 15,
      lineHeight: 20,
      fontWeight: '600' as const,
    },
  },
};
